from pathlib import Path
import csv,json
P=Path(__file__).resolve().parent
SOURCE='Falmouth_OCE_October2024_RevA.pdf'
def row(id,label,amount=None,rate=None,page=5,scope='',aliases=None):return dict(id=id,label=label,amount=amount,rate=rate,page=page,scope=scope,source=SOURCE,locator=label,aliases=aliases or [])
elements=[row('listing','Grade 2 Listing',None,0,scope='Source dash; not separately priced'),row('pitched_roof','Pitched Roof',418900,.2929),row('central_lantern','Central Lantern Feature',9600,.0067),row('rear_roof','Rear Roof (refer to Pitched Roof for costs)',400,.0003,aliases=['Rear Roof']),row('gutters','Valley and Parapet Gutters',16700,.0117),row('parapet','Parapet Walls',13800,.0096),row('rainwater','Rainwater Goods',47950,.0335),row('masonry','Masonry',110725,.0774),row('rendered','Rendered Masonry',7200,.005),row('windows','Windows',89450,.0625),row('rooflights','Rooflights',16100,.0113,aliases=['Rooflghts']),row('lantern_light','Lantern Light and Skylight',46950,.0328),row('doors','Doors',15000,.0105),row('walls','Walls',18200,.0127),row('services','Mechanical and Electrical Services',619250,.433,aliases=['M&E Services','Mechanical & Electrical Services'])]
summary=[row('building','Building Works',1430225,page=2),row('preliminaries','Main Contractors Preliminaries',182800,page=2,aliases=['Preliminaries']),row('overheads','Main Contractors Overheads & Profit',161303,.1,page=2,aliases=['Overheads and Profit','OH&P','Overheads & Profit']),row('building_estimate','Building Works Estimate',1774328,page=2),row('consultants','Project Consultants Fees','Excluded',page=2,scope='Excluded'),row('base','Base Cost Estimate',1774328,page=2),row('design_risk','Design Development Risks',177433,.1,page=2,aliases=['Design Development Risk','Design risk']),row('construction_risk','Construction Risks','-',page=2,scope='Source dash; no separate priced allowance'),row('employer_risk','Employer Change Risks','-',page=2,scope='Source dash; no separate priced allowance'),row('inflation_excluded','COST LIMIT (Inflation Excluded)',1951760,page=2),row('inflation','Inflation Allowance - 4Q24 to 1Q25',19518,.01,page=2,aliases=['Inflation Allowance','Inflation']),row('vat_excluded','COST LIMIT (VAT Excluded)',1971278,page=2,aliases=['Final Cost Limit','Cost Limit excluding VAT'])]
provisional=[row('timber','Structural appraisal of existing timbers',2000,page=4),row('opening_vents','Improve ventilation to opening vents on central lantern',1000,page=4),row('lantern_repairs','General repairs to central lantern',2000,page=4),row('venturi','Venturi System',10000,page=4),row('birds','Bird deterrent measures',25000,page=4),row('cills','Repairs to external cills',1500,page=4),row('external_doors','External doors (pair of) - 3nr',15000,page=4),row('heating_plant_area','External area for heating plant',2500,page=4),row('electrical','Electrical Power and Lighting',85750,page=4),row('water','Water Services',43500,page=4),row('heating','Heating',432000,page=4),row('ventilation','Ventilation',55000,page=4),row('scaffolding','Scaffolding (enclosed)',160000,page=4)]
for r in provisional:r['scope']='Included within elemental costs; memorandum only'
labels=["Objets d'art & all other art/decorative installations","Additional fit out items including specialist joinery","CCTV, smart systems","Specialist lighting installations and light fittings above standard","Soil investigation/contamination reports and resulting requirements","De-canting of building/rooms and re-install","M & E consultants or structural engineer design/specification/reports","Works/costs with onerous planning conditions particularly material specification","Professional Fees: Architect, Structural Engineer, Quantity Surveyor","Ecologist fees","CC Planning/Building Regulations Application/Inspection Fees","Legal fees","Interest and other financing costs","Increased foreign trade tariff costs surrounding UK withdrawal from EU","Increased costs from conflict in Ukraine and Middle East","Value Added Tax where applicable","Dry rot treatment","Asbestos removal"]
aliases=[['Art installations'],['Additional fit out'],['CCTV and smart systems'],['Specialist lighting'],['Soil investigation and contamination'],['Decanting and reinstallation'],['M&E and structural design fees'],['Onerous planning conditions'],['Professional fees'],[],['Planning and building regulation fees'],[],['Financing costs'],['Brexit tariff costs'],['Ukraine and Middle East conflict costs'],['VAT'],['Dry rot'],[]]
exclusions=[row('excluded_'+chr(97+i),label,'Excluded',page=3,scope='Excluded',aliases=als) for i,(label,als) in enumerate(zip(labels,aliases))]
for i,label in enumerate(['Above ground drainage','Fire Safety','Security/Access Control','AWC Call Alarms','Lightning Protection','Lift Works']):exclusions.append(row('excluded_services_'+str(i),label,'Excluded',page=4,scope='Excluded'))
qualifications=[row('guide','Guide to probable current cost',page=3,scope='Estimate is a guide only to probable current cost'),row('qs','Consultation with the Quantity Surveyor',page=3,scope='Study in consultation with the Quantity Surveyor'),row('drawings','Pre-planning drawings',page=3,scope='Based on RTP pre-planning drawings; no input from another designer'),row('scope_basis','Works as envisaged',page=3,scope='Works as envisaged in drawings and specifications in Basis of Estimate'),row('phase','Single phase contractor',page=3,scope='Single phase; local medium sized proficient contractor'),row('duration','Contract duration',page=3,scope='Contract duration not to exceed 45 weeks'),row('price_basis','Price basis and inflation period',page=3,scope='Rates at 4Q24 with inflation to 1Q25; BCIS indices not representative of Cornwall cost increases')]
facts=dict(identity={'document':'Order of Cost Estimate','revision':'A','date':'October 2024','project':'Municipal Building, The Moor, Falmouth','currency':'GBP','client':'Falmouth Town Council','job':'3959'},elements=elements,summary=summary,provisional=provisional,exclusions=exclusions,qualifications=qualifications)
(P/'source_facts.json').write_text(json.dumps(facts,ensure_ascii=False,indent=2))
for kind in ['elements','summary','provisional','exclusions','qualifications']:
 with (P/(kind+'_facts.csv')).open('w',newline='') as f:
  w=csv.DictWriter(f,fieldnames=['id','label','amount','rate','page','scope','source','locator']);w.writeheader();w.writerows({k:r[k] for k in w.fieldnames} for r in facts[kind])
assert sum(r['amount'] or 0 for r in elements)==1430225
(P/'source_visual_verification.json').write_text(json.dumps({'status':'PASS','page_count':5,'identity':facts['identity'],'pages_rendered_and_visually_reviewed':[1,2,3,4,5],'page5_cross_column_mappings':elements,'summary_printed_chain':summary,'provisional_count':len(provisional),'exclusion_count':len(exclusions),'provenance':'User-provided attachment, not a builder download'},indent=2))
print({k:len(facts[k]) for k in ['elements','summary','provisional','exclusions','qualifications']})
