from pathlib import Path
import json
P=Path(__file__).resolve().parents[1]
read=lambda name:json.loads((P/'metadata'/name).read_text())
r=read('validation_receipt.json');assert r['status']=='PASS';assert read('reference_verification.json')['status']=='PASS'
assert (P/'data/input_files/Falmouth_OCE_October2024_RevA.pdf').is_file()
for p in ['solution/reference.xlsx','metadata/source_facts.json','metadata/oracle_recompute.py','tests/evaluate.py','metadata/harbor_adapter.json']:assert (P/p).is_file(),p
status={'build_status':'BUILD_COMPLETE','task_version':'new6-c1-v1.0-falmouth','judge_version':'new6-c1-facts-v1.0','source_downloaded':False,'source_received_from_user':True,'source_visual_or_workbook_review_complete':True,'source_rights_review_complete':False,'source_rights_scope':'User provided public procurement attachment for this reconstruction; third-party redistribution license not independently cleared','agent_visible_package_ready':True,'reference_ready':True,'independent_oracle_ready':True,'evaluator_ready':True,'calibration_passed':True,'calibrated_cases':r['calibrated_cases'],'local_smoke_complete':True,'harbor_reference_smoke_complete':False,'agent_runs':0,'first_attempt_score':None,'agent_cost_usd':'0','formal_difficulty_verified':False,'human_acceptance_complete':False,'prompt_version':'natural-business-v2','verification_receipt':'metadata/validation_receipt.json','source_identity_receipt':'metadata/source_visual_verification.json','reference_verification':'metadata/reference_verification.json','known_limits':['Bounded English source-label and role-header parser; unsupported material layouts or legal unsupported formulas return JUDGE_ERROR, never zero','No third-party redistribution license determination','Formal difficulty requires actual agent run']}
(P/'metadata/build_status.json').write_text(json.dumps(status,indent=2));q=json.loads((P/'rubric.json').read_text());q['status']='CALIBRATED_READY';(P/'rubric.json').write_text(json.dumps(q,ensure_ascii=False,indent=2))
(P/'metadata/ready_for_first_run.json').write_text(json.dumps({'status':'READY_FOR_HARBOR_REFERENCE_SMOKE','task_version':status['task_version'],'judge_version':status['judge_version'],'calibration_cases':r['calibrated_cases'],'receipt':'metadata/validation_receipt.json','native_reference_score':'1','agent_calls':0,'input_files':['Falmouth_OCE_October2024_RevA.pdf','review_brief.md']},indent=2))
print(json.dumps(status))
