from pathlib import Path
import json,sys,openpyxl
p=Path(__file__).resolve().parents[1];sys.path[:0]=[str(p/'metadata'),str(p/'tests')];from oracle_recompute import compute;from evaluate import require_bound_source_layout,equal
fresh=next((p/'metadata/calibration/source_rows_reordered/base').glob('*/output/source_rows_reordered.xlsx'));w=openpyxl.load_workbook(fresh,data_only=True);n=0
for sn,base in [('Submodel1',True),('Submodel1s',False)]:
 for c,row in enumerate(compute(baseline=base),5):
  for key,r in {'investment_share':10,'capital_output_ratio':24,'gdp':52,'gdp_per_capita':33,'gdp_growth':31,'pc_growth':23}.items():assert equal(w[sn].cell(r,c).value,row[key]),(sn,r,c);n+=1
reference=next((p/'metadata/calibration/reference/base').glob('*/output/reference.xlsx'));require_bound_source_layout(openpyxl.load_workbook(reference,data_only=True),openpyxl.load_workbook(p/'metadata/configured_source.xlsx',data_only=False))
(p/'metadata/source_layout_equivalence.json').write_text(json.dumps({'status':'PASS','reordered_country_records':[240,241],'fresh_native_oracle_parity_facts':n,'new_source_coordinate_guard_accepts_existing_reference':True,'pending_reason':'Source facts are equivalent but current protection adapter cannot bind record relocation. No business score issued.'},indent=2))
m=p/'metadata';initial=m/'verification_initial_receipt.json'
if not initial.exists():initial.write_bytes((m/'verification_receipt.json').read_bytes())
first=json.loads(initial.read_text());rows={r['name']:r for r in first['results'] if r['passed']}
for name in ['verification_repair_receipt.json','verification_parser_receipt.json','verification_source_layout_receipt.json']:
 for r in json.loads((m/name).read_text())['results']:rows[r['name']]=r
manifest=json.loads((p/'fixtures/manifest.json').read_text());assert set(rows)=={c['name'] for c in manifest['cases']};assert all(r['passed'] for r in rows.values())
receipt={'task_id':p.name,'status':'PASS','calibrated_cases':len(rows),'results':list(rows.values()),'source_gate':'metadata/source_oracle_verification.json','reference_gate':'metadata/reference_verification.json','construction_gate':'metadata/construction_verification.json','prompt_review':'metadata/natural_prompt_review_receipt.json','repaired_categories':['source protection: shared-formula followers preserved outside cleared block','fixture type: isolated constant per-capita-output offset instead of changing dependent investment/capital','parse boundary: partial result table, required engine errors, and moved source records'],'agent_calls':0,'agent_cost_usd':'0','formal_difficulty_qualified':False,'required_fact_denominators':{'R001':16,'R002':136,'R003':136,'R004':822,'R005':104,'R006':19},'external_acceptance_gaps':['Full agentic prose-claim review','Externally applicable negative-item policy acceptance','External redistribution rights review','Formal specified-system difficulty protocol']}
(m/'verification_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2));(m/'validation_receipt.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2));(m/'reference_score.json').write_bytes((m/'calibration/reference/evaluation.json').read_bytes())
status={'build_status':'BUILD_COMPLETE','source_downloaded':True,'source_visual_or_workbook_review_complete':True,'source_rights_review_complete':False,'source_rights_scope':'Public source intended local model use reviewed; external redistribution not independently cleared','original_source_country':'Peru','configured_task_country':'Zambia','agent_visible_package_ready':True,'reference_ready':True,'independent_oracle_ready':True,'native_source_recalc_passed':True,'evaluator_ready':True,'calibration_passed':True,'calibrated_cases':len(rows),'local_smoke_complete':True,'harbor_reference_smoke_complete':False,'agent_runs':0,'first_attempt_score':None,'agent_cost_usd':'0','formal_difficulty_verified':False,'human_acceptance_complete':False,'prompt_version':'natural-business-v2','task_version':'new6-a2-v1.0-zambia','judge_version':'new6-a2-facts-v1.0','verification_receipt':'metadata/verification_receipt.json','known_limits':receipt['external_acceptance_gaps']}
(m/'build_status.json').write_text(json.dumps(status,ensure_ascii=False,indent=2))
r=json.loads((p/'rubric.json').read_text());r.update(task_version='new6-a2-v1.0-zambia',judge_version='new6-a2-facts-v1.0',status='IMPLEMENTED_CALIBRATED_LOCAL_SMOKE_READY',fact_denominators=receipt['required_fact_denominators']);(p/'rubric.json').write_text(json.dumps(r,ensure_ascii=False,indent=2))
print('READY:',len(rows),'calibrated cases;',n,'source-reordered native parity facts')
